pull_request_rules:
  - name: merge automatically when CI passes and PR is approved
    conditions:
      - check-success = "lint"
      - check-success = "pre-commit.ci - pr"
      - check-success = "test (3.10)"
      - check-success = "test (3.11)"
      - check-success = "test (3.12)"
      - or:
        - approved-reviews-by = nim65s
        - author = nim65s
        - author = pre-commit-ci[bot]
        - author = dependabot[bot]
    actions:
      merge:
