repos:
- repo: https://github.com/astral-sh/ruff-pre-commit
  rev: v0.12.10
  hooks:
  - id: ruff
    args:
    - --fix
    - --exit-non-zero-on-fix
  - id: ruff-format
- repo: https://github.com/nim65s/pre-commit-sort
  rev: v0.4.0
  hooks:
  - id: pre-commit-sort
- repo: https://github.com/pappasam/toml-sort
  rev: v0.24.2
  hooks:
  - id: toml-sort-fix
- repo: https://github.com/pre-commit/mirrors-mypy
  rev: v1.17.1
  hooks:
  - id: mypy
    additional_dependencies:
    - django-autoslug
    - django-bootstrap5
    - django-stubs
    - types-markdown
    - types-setuptools
    - types-toml
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v6.0.0
  hooks:
  - id: check-added-large-files
  - id: check-ast
  - id: check-merge-conflict
  - id: check-symlinks
  - id: check-toml
  - id: check-yaml
  - id: debug-statements
  - id: detect-private-key
  - id: end-of-file-fixer
  - id: mixed-line-ending
  - id: trailing-whitespace
- repo: https://gitlab.com/smop/pre-commit-hooks
  rev: v1.0.0
  hooks:
  - id: check-gitlab-ci
exclude: .*/migrations/.*
