name: Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10", "3.11", "3.12", "3.13", "3.14"]
    steps:
      - uses: actions/checkout@v5
      - run: sudo apt update && sudo apt install -qy libxml2 libxslt1-dev
      - uses: astral-sh/setup-uv@v6
        with:
          python-version: "${{ matrix.python-version }}"
      - name: setup
        run: uv sync --dev
      - run: uv run ./manage.py migrate
        env:
          PYTHONWARNINGS: error
      - run: uv run coverage run manage.py test
        env:
          PYTHONWARNINGS: error

      - uses: codecov/codecov-action@v5
