name: Tests

on:
  push:
    branches:
    - main
  pull_request:
    branches:
    - main

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.10","3.11","3.12", "3.13"]
    steps:
      - uses: actions/checkout@v4
      - run: pipx install poetry
      - uses: actions/setup-python@v5
        with:
          python-version: ${{ matrix.python-version }}
          cache: poetry
      - name: setup
        run: poetry install --no-interaction --no-ansi
      - run: poetry run ./manage.py migrate
        env:
          PYTHONWARNINGS: error
      - run: poetry run coverage run manage.py test
        env:
          PYTHONWARNINGS: error
      - run: python -m pip install "git+https://github.com/${GITHUB_REPOSITORY}.git#egg=dmdm"

      - uses: codecov/codecov-action@v5
